name: "workspace-cleanup-action"
description: "Cleans the GitHub Workspace"
author: "lokeshkamalay"
inputs:
  directory:
    description: Directory to change the ownership
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "docker" # check out options here https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
  image: 'Dockerfile'
