name: Cleaningup with Workspace

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cleaning up workspace
        uses: ./